export enum CaseEvent {
  DEFENDANT_RESPONSE_SPEC  = 'DEFENDANT_RESPONSE_SPEC',
  DEFENDANT_RESPONSE_CUI  = 'DEFENDANT_RESPONSE_CUI',
  INFORM_AGREED_EXTENSION_DATE_SPEC ='INFORM_AGREED_EXTENSION_DATE_SPEC',
  CREATE_LIP_CLAIM = 'CREATE_LIP_CLAIM',
  UPDATE_CASE_STATE_CASE_SETTLED = 'UPDATE_CASE_STATE_CASE_SETTLED'
}
