export enum CaseEvent {
  DEFENDANT_RESPONSE_SPEC  = 'DEFENDANT_RESPONSE_SPEC',
  DEFENDANT_RESPONSE_CUI  = 'DEFENDANT_RESPONSE_CUI',
  INFORM_AGREED_EXTENSION_DATE_SPEC ='INFORM_AGREED_EXTENSION_DATE_SPEC',
  CREATE_LIP_CLAIM = 'CREATE_LIP_CLAIM',
  DEFENDANT_TRIAL_ARRANGEMENTS = 'TRIAL_READINESS',
}
