export enum CaseEvent {
  DEFENDANT_RESPONSE_SPEC  = 'DEFENDANT_RESPONSE_SPEC',
  DEFENDANT_RESPONSE_CUI  = 'DEFENDANT_RESPONSE_CUI',
  INFORM_AGREED_EXTENSION_DATE_SPEC ='INFORM_AGREED_EXTENSION_DATE_SPEC',
  CREATE_LIP_CLAIM = 'CREATE_LIP_CLAIM',
  DEFAULT_JUDGEMENT_SPEC = 'DEFAULT_JUDGEMENT_SPEC',
  ENTER_BREATHING_SPACE_LIP = 'ENTER_BREATHING_SPACE_LIP',
  CREATE_CLAIM_SPEC_AFTER_PAYMENT = 'CREATE_CLAIM_SPEC_AFTER_PAYMENT',
}
