export enum TabLabel {

  LATEST_UPDATE = 'PAGES.CLAIM_SUMMARY.LATEST_UPDATE',
  UPDATES = 'PAGES.CLAIM_SUMMARY.UPDATES',
  DOCUMENTS = 'PAGES.CLAIM_SUMMARY.DOCUMENTS',
  NOTICES = 'PAGES.CLAIM_SUMMARY.NOTICES_AND_ORDERS',
  BUNDLES = 'PAGES.CLAIM_SUMMARY.BUNDLES.TAB_TITLE'

}

export enum TabId {
  LATEST_UPDATE = 'latest-updates',
  UPDATES = 'updates',
  DOCUMENTS = 'documents',
  NOTICES = 'notices-orders',
  BUNDLES = 'bundles'
}
