export enum ClaimantIntention {
  NOT_TO_PROCEED_WITH_CLAIM = 'NOT_TO_PROCEED_WITH_CLAIM',
  ACCEPTED_DEFENDANT_RESPONSE = 'ACCEPTED_DEFENDANT_RESPONSE',
  REJECTED_DEFENDANT_RESPONSE = 'REJECTED_DEFENDANT_RESPONSE',
  PROPOSED_DIFFERENT_REPAYMENT_PLAN = 'PROPOSED_DIFFERENT_REPAYMENT_PLAN',
  SIGNED_SETTLEMENT_AGREEMENT = 'SIGNED_SETTLEMENT_AGREEMENT',
  ACCEPTED_PLAN_AND_REQUESTED_CCJ = 'ACCEPTED_PLAN_AND_REQUESTED_CCJ',
  REJECTED_PLAN_AND_REQUESTED_CCJ = 'REJECTED_PLAN_AND_REQUESTED_CCJ',
  REJECTED_PLAN_AND_AGREED_MEDIATION = 'REJECTED_PLAN_AND_AGREED_MEDIATION',
}
