export enum ApplicationState {
  ADDITIONAL_RESPONSE_TIME_EXPIRED = 'ADDITIONAL_RESPONSE_TIME_EXPIRED',
  ADDITIONAL_RESPONSE_TIME_PROVIDED = 'ADDITIONAL_RESPONSE_TIME_PROVIDED',
  APPLICATION_ADD_PAYMENT = 'APPLICATION_ADD_PAYMENT',
  APPLICATION_CLOSED = 'APPLICATION_CLOSED',
  APPLICATION_DISMISSED = 'APPLICATION_DISMISSED',
  APPLICATION_PAYMENT_FAILED = 'APPLICATION_PAYMENT_FAILED',
  APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION = 'APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION',
  AWAITING_ADDITIONAL_INFORMATION = 'AWAITING_ADDITIONAL_INFORMATION',
  AWAITING_APPLICATION_PAYMENT = 'AWAITING_APPLICATION_PAYMENT',
  AWAITING_DIRECTIONS_ORDER_DOCS = 'AWAITING_DIRECTIONS_ORDER_DOCS',
  AWAITING_RESPONDENT_RESPONSE = 'AWAITING_RESPONDENT_RESPONSE',
  AWAITING_WRITTEN_REPRESENTATIONS = 'AWAITING_WRITTEN_REPRESENTATIONS',
  HEARING_SCHEDULED = 'HEARING_SCHEDULED',
  LISTING_FOR_A_HEARING = 'LISTING_FOR_A_HEARING',
  ORDER_MADE = 'ORDER_MADE',
  PENDING_APPLICATION_ISSUED = 'PENDING_APPLICATION_ISSUED',
  PROCEEDS_IN_HERITAGE = 'PROCEEDS_IN_HERITAGE',
  RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION = 'RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION',
}

export enum ApplicationStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  TO_DO = 'TO_DO',
  COMPLETE = 'COMPLETE',
}

export class ApplicationSummary {
  state: ApplicationState;
  status: ApplicationStatus;
  statusColor?: string;
  types: string;
  id: string;
  createdDate: string;
  applicationUrl: string;
}

export const StatusColor: Record<ApplicationStatus, string> = {
  [ApplicationStatus.IN_PROGRESS]: 'govuk-tag--green',
  [ApplicationStatus.TO_DO]: 'govuk-tag--red',
  [ApplicationStatus.COMPLETE]: 'govuk-tag--blue',
};
