export enum debtPaymentOptions {
  UPLOAD_EVIDENCE_DEBT_PAID_IN_FULL = 'UPLOAD_EVIDENCE_DEBT_PAID_IN_FULL',
  MADE_FULL_PAYMENT_TO_COURT = 'MADE_FULL_PAYMENT_TO_COURT',
  UNABLE_TO_PROVIDE_EVIDENCE_OF_FULL_PAYMENT = 'UNABLE_TO_PROVIDE_EVIDENCE_OF_FULL_PAYMENT',
}
