export enum debtPaymentOptions {
  UPLOAD_EVIDENCE = 'PAGES.GENERAL_APPLICATION.DEBT_PAYMENT.UPLOAD_EVIDENCE',
  MADE_FULL_PAYMENT = 'PAGES.GENERAL_APPLICATION.DEBT_PAYMENT.MADE_FULL_PAYMENT',
  NO_EVIDENCE = 'PAGES.GENERAL_APPLICATION.DEBT_PAYMENT.NO_EVIDENCE',
}
