export enum CcdSupportRequirement {
  DISABLED_ACCESS = 'DISABLED_ACCESS',
  HEARING_LOOPS = 'HEARING_LOOPS',
  SIGN_INTERPRETER = 'SIGN_INTERPRETER',
  LANGUAGE_INTERPRETER = 'LANGUAGE_INTERPRETER',
  OTHER_SUPPORT = 'OTHER_SUPPORT',
}
