export enum DocumentType {
  SEALED_CLAIM = 'SEALED_CLAIM',
  ACKNOWLEDGEMENT_OF_CLAIM = 'ACKNOWLEDGEMENT_OF_CLAIM',
  ACKNOWLEDGEMENT_OF_SERVICE = 'ACKNOWLEDGEMENT_OF_SERVICE',
  DIRECTIONS_QUESTIONNAIRE = 'DIRECTIONS_QUESTIONNAIRE',
  DEFENDANT_DEFENCE = 'DEFENDANT_DEFENCE',
  DEFENDANT_DRAFT_DIRECTIONS ='DEFENDANT_DRAFT_DIRECTIONS',
  DEFAULT_JUDGMENT = 'DEFAULT_JUDGMENT',
  CLAIMANT_DEFENCE = 'CLAIMANT_DEFENCE',
  CLAIMANT_DRAFT_DIRECTIONS = 'CLAIMANT_DRAFT_DIRECTIONS'
}
