export enum DocumentType {
  SEALED_CLAIM = 'SEALED_CLAIM',
  ACKNOWLEDGEMENT_OF_CLAIM = 'ACKNOWLEDGEMENT_OF_CLAIM',
  ACKNOWLEDGEMENT_OF_SERVICE = 'ACKNOWLEDGEMENT_OF_SERVICE',
  DIRECTIONS_QUESTIONNAIRE = 'DIRECTIONS_QUESTIONNAIRE',
  DEFENDANT_DEFENCE = 'DEFENDANT_DEFENCE',
  DEFENDANT_DRAFT_DIRECTIONS ='DEFENDANT_DRAFT_DIRECTIONS',
  DEFAULT_JUDGMENT = 'DEFAULT_JUDGMENT',
  CLAIMANT_DEFENCE = 'CLAIMANT_DEFENCE',
  CLAIMANT_DRAFT_DIRECTIONS = 'CLAIMANT_DRAFT_DIRECTIONS'
}

export enum DocumentUri {
  SEALED_CLAIM = 'sealed-claim',
  ACKNOWLEDGEMENT_OF_CLAIM = 'acknowledgement-of-claim',
  ACKNOWLEDGEMENT_OF_SERVICE = 'acknowledgement-of-service',
  DIRECTIONS_QUESTIONNAIRE = 'directions-questionnaire',
  DEFENDANT_DEFENCE = 'defendant-defence',
  DEFENDANT_DRAFT_DIRECTIONS = 'defendant-draft-directions',
  DEFAULT_JUDGMENT = 'default-judgement',
  CLAIMANT_DEFENCE = 'claimant-defence',
  CLAIMANT_DRAFT_DIRECTIONS = 'claimant-draft-directions'
}
