export enum DashboardStatus {
  PAID_IN_FULL = 'PAID_IN_FULL',
  CLAIMANT_ACCEPTED_STATES_PAID = 'CLAIMANT_ACCEPTED_STATES_PAID',
  PAID_IN_FULL_CCJ_CANCELLED = 'PAID_IN_FULL_CCJ_CANCELLED',
  PAID_IN_FULL_CCJ_SATISFIED = 'PAID_IN_FULL_CCJ_SATISFIED',
  TRANSFERRED = 'TRANSFERRED',
  REDETERMINATION_BY_JUDGE = 'REDETERMINATION_BY_JUDGE',
}
