export enum DefendantResponseStatus {
  NO_RESPONSE = 'NO_RESPONSE',
  ELIGIBLE_FOR_CCJ_AFTER_FULL_ADMIT_PAY_IMMEDIATELY_PAST_DEADLINE = 'ELIGIBLE_FOR_CCJ_AFTER_FULL_ADMIT_PAY_IMMEDIATELY_PAST_DEADLINE',
  ELIGIBLE_FOR_CCJ = 'ELIGIBLE_FOR_CCJ',
  MORE_TIME_REQUESTED = 'MORE_TIME_REQUESTED',
  PAID_IN_FULL = 'PAID_IN_FULL',
  CLAIMANT_ACCEPTED_STATES_PAID = 'CLAIMANT_ACCEPTED_STATES_PAID',
  PAID_IN_FULL_CCJ_CANCELLED = 'PAID_IN_FULL_CCJ_CANCELLED',
  PAID_IN_FULL_CCJ_SATISFIED = 'PAID_IN_FULL_CCJ_SATISFIED',
  TRANSFERRED = 'TRANSFERRED',
  REDETERMINATION_BY_JUDGE = 'REDETERMINATION_BY_JUDGE'
}
