import {OtherDependants} from '../form/models/statementOfMeans/otherDependants';
import {CitizenBankAccount} from './citizenBankAccount';
import {Residence} from '../form/models/statementOfMeans/residence';
import {Employment} from './employment';
import {Employers} from '../form/models/statementOfMeans/employment/employers';
import {Dependants} from '../form/models/statementOfMeans/dependants/dependants';
import {PriorityDebts} from '../form/models/statementOfMeans/priorityDebts';
import {SelfEmployedAs} from './selfEmployedAs';
import {TaxPayments} from './taxPayments';
import {Unemployment} from '../form/models/statementOfMeans/unemployment/unemployment';
import {RegularExpenses} from '../form/models/statementOfMeans/expensesAndIncome/regularExpenses';
import {Debts} from '../form/models/statementOfMeans/debts/debts';
import {CourtOrders} from '../form/models/statementOfMeans/courtOrders/courtOrders';
import {Explanation} from '../form/models/statementOfMeans/explanation';
import {RegularIncome} from '../form/models/statementOfMeans/expensesAndIncome/regularIncome';
import {GenericYesNo} from '../form/models/genericYesNo';

export class StatementOfMeans {
  disability?: GenericYesNo;
  severeDisability?: GenericYesNo;
  partnerAge?: GenericYesNo;
  bankAccounts?: CitizenBankAccount[];
  otherDependants?: OtherDependants;
  cohabiting?: GenericYesNo;
  employment?: Employment;
  employers?: Employers;
  taxPayments?: TaxPayments;
  partnerDisability?: GenericYesNo;
  partnerSevereDisability?: GenericYesNo;
  residence?: Residence;
  partnerPension?: GenericYesNo;
  dependants?: Dependants;
  numberOfChildrenLivingWithYou?: number;
  selfEmployedAs?: SelfEmployedAs;
  unemployment?: Unemployment;
  childrenDisability?: GenericYesNo;
  priorityDebts?: PriorityDebts;
  regularExpenses?: RegularExpenses;
  debts?: Debts;
  courtOrders?: CourtOrders;
  carer?: GenericYesNo;
  explanation?: Explanation;
  regularIncome?: RegularIncome;
}
