export const CLAIM_ID = 'claimId';

// -- Summary Section Array Index
export const INDEX_DETAILS_SECTION = 0;
export const INDEX_RESPONSE_CLAIM_SECTION = 2;
export const INDEX_FINANCIAL_SECTION = 4;

export const INDEX_RESPONSE_CLAIM_SECTION_PART_ADMISSION = 3;
export const INDEX_FINANCIAL_SECTION_PART_ADMISSION = 5;

export const INDEX_RESPONSE_DETAILS_SECTION = 1;
export const INDEX_RESPONSE_PAYMENT_SECTION = 6;
export const INDEX_RESPONSE_FREE_TELEPHONE_MEDIATION_SECTION = 7;

// -- Section Titles
export const PAGES_CHECK_YOUR_ANSWER_YOUR_FINANCIAL_DETAILS_TITLE = 'PAGES.CHECK_YOUR_ANSWER.YOUR_FINANCIAL_DETAILS_TITLE';
export const PAGES_CHECK_YOUR_ANSWER_BANK_AND_SAVINGS_ACCOUNTS = 'PAGES.CHECK_YOUR_ANSWER.BANK_AND_SAVINGS_ACCOUNTS';
export const PAGES_CHECK_YOUR_ANSWER_BANK_TYPE_OF_ACCOUNT = 'PAGES.CHECK_YOUR_ANSWER.BANK_TYPE_OF_ACCOUNT';
export const PAGES_CHECK_YOUR_ANSWER_BANK_BALANCE = 'PAGES.CHECK_YOUR_ANSWER.BANK_BALANCE';
export const PAGES_CHECK_YOUR_ANSWER_BANK_JOINT_ACCOUNT = 'PAGES.CHECK_YOUR_ANSWER.BANK_JOINT_ACCOUNT';
export const PAGES_CHECK_YOUR_ANSWER_CHILDREN = 'PAGES.CHECK_YOUR_ANSWER.CHILDREN';
export const PAGES_CHECK_YOUR_ANSWER_CHILDREN_DO_YOU_HAVE_ANY_LIVE_WITH_YOU = 'PAGES.CHECK_YOUR_ANSWER.CHILDREN_DO_YOU_HAVE_ANY_LIVE_WITH_YOU';
export const PAGES_CHECK_YOUR_ANSWER_SUPPORT_ANYONE_ELSE_FINANCIALLY = 'PAGES.CHECK_YOUR_ANSWER.SUPPORT_ANYONE_ELSE_FINANCIALLY';
export const PAGES_CHECK_YOUR_ANSWER_DISABILITY_ARE_YOU_DISABLED = 'PAGES.CHECK_YOUR_ANSWER.DISABILITY_ARE_YOU_DISABLED';
export const PAGES_CHECK_YOUR_ANSWER_DISABILITY_ARE_YOU_SEVERELY_DISABLED = 'PAGES.CHECK_YOUR_ANSWER.DISABILITY_ARE_YOU_SEVERELY_DISABLED';
export const PAGES_CHECK_YOUR_ANSWER_WHERE_DO_YOU_LIVE = 'PAGES.CHECK_YOUR_ANSWER.WHERE_DO_YOU_LIVE';
export const PAGES_CHECK_YOUR_ANSWER_PARTNER_DO_YOU_LIVE_WITH_A = 'PAGES.CHECK_YOUR_ANSWER.PARTNER_DO_YOU_LIVE_WITH_A';
export const PAGES_CHECK_YOUR_ANSWER_CARER_CREDIT_DO_YOU_CLAIM = 'PAGES.CHECK_YOUR_ANSWER.CARER_CREDIT_DO_YOU_CLAIM';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_DETAILS = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_DETAILS';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_TYPE = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_TYPE';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_NAME = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_NAME';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_DO_YOU_HAVE_A_JOB = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_DO_YOU_HAVE_A_JOB';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_WHO_EMPLOYS_YOU = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_WHO_EMPLOYS_YOU';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_JOB_TITLE = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_JOB_TITLE';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_SELF_DETAILS = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_SELF_DETAILS';
export const PAGES_CHECK_YOUR_ANSWER_EMPLOYMENT_SELF_ANNUAL_TURNOVER = 'PAGES.CHECK_YOUR_ANSWER.EMPLOYMENT_SELF_ANNUAL_TURNOVER';
export const PAGES_CHECK_YOUR_ANSWER_TAX_PAYMENT_ARE_YOU_BEHIND = 'PAGES.CHECK_YOUR_ANSWER.TAX_PAYMENT_ARE_YOU_BEHIND';
export const PAGES_CHECK_YOUR_ANSWER_TAX_PAYMENT_AMOUNT_YOU_OWE = 'PAGES.CHECK_YOUR_ANSWER.TAX_PAYMENT_AMOUNT_YOU_OWE';
export const PAGES_CHECK_YOUR_ANSWER_TAX_PAYMENT_REASON = 'PAGES.CHECK_YOUR_ANSWER.TAX_PAYMENT_REASON';
export const PAGES_CHECK_YOUR_ANSWER_COURT_ORDERS_TITLE = 'PAGES.CHECK_YOUR_ANSWER.COURT_ORDERS_TITLE';
export const PAGES_CHECK_YOUR_ANSWER_COURT_ORDERS_CLAIM_NUMBER = 'PAGES.CHECK_YOUR_ANSWER.COURT_ORDERS_CLAIM_NUMBER';
export const PAGES_CHECK_YOUR_ANSWER_COURT_ORDERS_AMOUNT_OWNED = 'PAGES.CHECK_YOUR_ANSWER.COURT_ORDERS_AMOUNT_OWNED';
export const PAGES_CHECK_YOUR_ANSWER_COURT_ORDERS_MONTHLY_INSTALMENT = 'PAGES.CHECK_YOUR_ANSWER.COURT_ORDERS_MONTHLY_INSTALMENT';
export const PAGES_CHECK_YOUR_ANSWER_DEBTS_LOANS_OR_CREDIT_CARDS = 'PAGES.CHECK_YOUR_ANSWER.DEBTS_LOANS_OR_CREDIT_CARDS';
export const PAGES_CHECK_YOUR_ANSWER_DEBT = 'PAGES.CHECK_YOUR_ANSWER.DEBT';
export const PAGES_CHECK_YOUR_ANSWER_DEBTS_TOTAL_OWED = 'PAGES.CHECK_YOUR_ANSWER.DEBTS_TOTAL_OWED';
export const PAGES_CHECK_YOUR_ANSWER_DEBTS_MONTHLY_PAYMENTS = 'PAGES.CHECK_YOUR_ANSWER.DEBTS_MONTHLY_PAYMENTS';
export const PAGES_CHECK_YOUR_ANSWER_PRIORITY_DEBTS_YOU_ARE_BEHIND_ON = 'PAGES.CHECK_YOUR_ANSWER.PRIORITY_DEBTS_YOU_ARE_BEHIND_ON';
export const PAGES_CHECK_YOUR_ANSWER_PRIORITY_DEBT_TYPE = 'PAGES.CHECK_YOUR_ANSWER.PRIORITY_DEBT_TYPE';
export const PAGES_CHECK_YOUR_ANSWER_PRIORITY_DEBT_ARREARS_REPAYMENT = 'PAGES.CHECK_YOUR_ANSWER.PRIORITY_DEBT_ARREARS_REPAYMENT';
export const PAGES_CHECK_YOUR_ANSWER_EXPENSES_REGULAR = 'PAGES.CHECK_YOUR_ANSWER.EXPENSES_REGULAR';
export const PAGES_CHECK_YOUR_ANSWER_INCOME_REGULAR = 'PAGES.CHECK_YOUR_ANSWER.INCOME_REGULAR';
export const PAGES_CHECK_YOUR_ANSWER_CHANGE = 'PAGES.CHECK_YOUR_ANSWER.CHANGE';
