civil-service:
  enabled: true
  java:
    applicationPort: 4000
    releaseNameOverride: ${SERVICE_NAME}-civil-service
    image: 'hmctspublic.azurecr.io/civil/service:latest'
    imagePullPolicy: Always
    ingressHost: ${SERVICE_NAME}-civil-service.preview.platform.hmcts.net
    devcpuRequests: 500m
    devmemoryRequests: 2048Mi
    devmemoryLimits: 4096Mi
    secrets:
      CMC_DB_PASSWORD:
        secretRef: "{{ .Values.global.postgresSecret }}"
        key: PASSWORD
        disabled: false
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - name: civil-idam-client-secret
            alias: CIVIL_CLIENT_SECRET
          - name: microservicekey-civil-service
            alias: idam.s2s-auth.totp_secret
          - name: system-update-user-username
            alias: CIVIL_SYSTEM_UPDATE_USERNAME
          - name: system-update-user-password
            alias: CIVIL_SYSTEM_UPDATE_PASSWORD
          - name: cross-access-user-username
            alias: CIVIL_CROSS_ACCESS_USERNAME
          - name: cross-access-user-password
            alias: CIVIL_CROSS_ACCESS_PASSWORD
          - name: prd-admin-user-username
            alias: CIVIL_PRD_ADMIN_USERNAME
          - name: prd-admin-user-password
            alias: CIVIL_PRD_ADMIN_PASSWORD
          - name: docmosis-api-key
            alias: docmosis.tornado.key
          - name: gov-notify-pretends-api-key
            alias: GOV_NOTIFY_API_KEY
          - name: sendgrid-api-key
            alias: SENDGRID_API_KEY
          - name: robotics-notification-sender
            alias: robotics.notification.sender
          - name: robotics-notification-recipient
            alias: robotics.notification.recipient
          - name: launch-darkly-sdk-key-non-prod
            alias: LAUNCH_DARKLY_SDK_KEY
          - name: robotics-notification-multipartyrecipient
            alias: robotics.notification.multipartyrecipient
          - name: robotics-notification-recipient-spec
            alias: robotics.notification.specRecipient
          - name: robotics-notification-recipient-lipj
            alias: robotics.notification.lipJRecipient
          - name: ordnance-survey-api-key
            alias: OS_POSTCODE_LOOKUP_API_KEY
          - name: notification-caseworker-spec-receiver
            alias: notification.caseworker.spec.receiver
          - name: mediation-notification-sender
            alias: mediation.emails.sender
          - name: mediation-notification-recipient
            alias: mediation.emails.recipient
          - name: hmc-servicebus-shared-access-key-tf
            alias: HMC_HEARINGS_TOPIC_ACCESS_KEY
    environment:
      IDAM_CLIENT_ID: civil-service
      IDAM_CLIENT_REDIRECT_URI: https://civil-ccd-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback
      IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
      IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
      IDAM_END_SESSION_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/endSession
      IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      MANAGE_CASE_UI_BASE_URL: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net
      SPRING_SECURITY_ENABLED: true
      CMC_DB_PORT: 5432
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/jwks
      AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
      TESTING_SUPPORT_ENABLED: true
      FEES_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      PAYMENTS_API_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      SEND_LETTER_URL: http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      CUI_URL: https://${SERVICE_FQDN}
      CUI_URL_RESPOND_TO_CLAIM: https://${SERVICE_FQDN}/first-contact/start
      CLAIM_STORE_URL: http://cmc-claim-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      GENAPP_LRD_URL: http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      GENAPP_JRD_URL: http://rd-judicial-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      DOCMOSIS_TORNADO_URL: https://docmosis.aat.platform.hmcts.net
      DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      SPRING_CLOUD_BOOTSTRAP_ENABLED: true
      RD_PROFESSIONAL_API_URL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      RD_COMMONDATA_API_URL: http://rd-commondata-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
      LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
      CORE_CASE_DATA_API_URL: http://${SERVICE_NAME}-ccd-data-store-api
      CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
      REFERENCE_DATABASE_MIGRATION: true
      CAMUNDA_URL: http://${SERVICE_NAME}-camunda/engine-rest/
      POLLING_EVENT_EMITTER_ENABLED: false
      DOCUMENT_MANAGEMENT_SECURED: true
      STITCHING_API_ENABLED: false
      SERVICE_REQUEST_UPDATE: https://${SERVICE_NAME}-civil-service.preview.platform.hmcts.net/service-request-update
      SERVICE_REQUEST_UPDATE_CLAIM_ISSUED: https://${SERVICE_NAME}-civil-service.preview.platform.hmcts.net/service-request-update-claim-issued
      CIVIL_S2S_AUTHORISED_SERVICES: payment_app,ccd_data,civil_service,civil-citizen-ui
      ACA_SERVICE_API_BASEURL: http://${SERVICE_NAME}-aac-manage-case-assignment
      CMC_DB_HOST: civil-preview.postgres.database.azure.com
      CMC_DB_CONNECTION_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CMC_DB_USERNAME: hmcts
      CMC_DB_NAME: "pr-${CHANGE_ID}-cmc"
    postgresql:
      enabled: false

aac-manage-case-assignment:
  enabled: true
  java:
    disableKeyVaults: true
    ingressHost: manage-case-assignment-${SERVICE_NAME}.preview.platform.hmcts.net
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-aac-manage-case-assignment
    image: hmctspublic.azurecr.io/aac/manage-case-assignment:latest
    environment:
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
      OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      MCA_DS_PROXY_URLS_ALLOWED_LIST: /searchCases.*,/internal/searchCases.*,/internal/cases.*
      MCA_DEF_STORE_PROXY_URLS_ALLOWED_LIST: /api/display/challenge-questions.*
      MANAGE_CASE_S2S_AUTHORISED_SERVICES: xui_webapp,ccd_data,fpl_case_service,divorce_frontend,divorce_ccd_submission,finrem_case_orchestration,civil_service,civil_general_applications
      CCD_DATA_STORE_API_BASE_URL: http://${SERVICE_NAME}-ccd-data-store-api
      CCD_DEFINITION_STORE_API_BASE_URL: http://${SERVICE_NAME}-ccd-definition-store-api
      PRD_HOST: http://rd-professional-api-aat.service.core-compute-aat.internal
      IDAM_CAA_USERNAME: ${IDAM_CAA_USERNAME}
      IDAM_CAA_PASSWORD: ${IDAM_CAA_PASSWORD}
      IDAM_CLIENT_SECRET: ${IDAM_MCA_CLIENT_SECRET}
      MANAGE_CASE_S2S_KEY: ${MANAGE_CASE_S2S_KEY}
      IDAM_NOC_APPROVER_USERNAME: ${IDAM_NOC_APPROVER_USERNAME}
      IDAM_NOC_APPROVER_PASSWORD: ${IDAM_NOC_APPROVER_PASSWORD}
      NOTIFY_MCA_API_KEY: ${NOTIFY_MCA_API_KEY}
    autoscaling:
      enabled: false

idam-pr:
  releaseNameOverride: ${SERVICE_NAME}-xui-idam-pr
  enabled: true
  redirect_uris:
    Civil Citizen UI:
      - https://${SERVICE_NAME}.preview.platform.hmcts.net/oauth2/callback
    XUI:
      - https://xui-${SERVICE_NAME}.preview.platform.hmcts.net/oauth2/callback

xui-webapp:
  enabled: true
  memoryLimits: 1Gi
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    devcpuRequests: 500m
    devmemoryRequests: 1Gi
    devcpuLimits: 1
    devmemoryLimits: 2Gi
    environment:
      HEALTH_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal/health
      HEALTH_WORK_ALLOCATION_TASK_API: https://wa-task-management-api-${SERVICE_FQDN}.preview.platform.hmcts.net/health
      SERVICES_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_TERMS_AND_CONDITIONS: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal
      SERVICES_WORK_ALLOCATION_TASK_API: http://{{ .Release.Name }}-wa-task-management-api
      SERVICES_WA_WORKFLOW_API_URL: http://wa-workflow-api-${SERVICE_FQDN}
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://${SERVICE_NAME}-aac-manage-case-assignment
      JURISDICTIONS: CIVIL
      LAUNCH_DARKLY_CLIENT_ID: ~
      WA_SUPPORTED_JURISDICTIONS: "IA,PRIVATELAW"

ccd:
  enabled: true
  ccd:
    adminWeb:
      enabled: false
    apiGatewayWeb:
      enabled: true
    definitionImporter:
      enabled: false
    managementWeb:
      enabled: false
    s2s:
      enabled: false
    postgresql:
      enabled: false
    ras:
      enabled: false
    userProfileImporter:
      enabled: false
    userProfile:
      enabled: false

  global:
    postgresUsername: hmcts
    postgresSecret: postgres
    postgresHostname: civil-preview.postgres.database.azure.com
    databaseNamePrefix: "pr-${CHANGE_ID}-"
    ccdApiGatewayIngress: http://${SERVICE_NAME}-ccd-api-gw
    ccdDataStoreUrl: http://${SERVICE_NAME}-ccd-data-store-api
    ccdDefinitionStoreUrl: http://${SERVICE_NAME}-ccd-definition-store-api
    ccdUserProfileUrl: http://ccd-user-profile-api-aat.service.core-compute-aat.internal
    dmStoreUrl: http://dm-store-aat.service.core-compute-aat.internal
    idamApiUrl: https://idam-api.aat.platform.hmcts.net
    idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    postgresPassword: ${POSTGRES_PASSWORD}
    s2sUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

  ccd-api-gateway-web:
    nodejs:
      image: hmctspublic.azurecr.io/ccd/api-gateway-web:latest
      imagePullPolicy: Always
      environment:
        ADDRESS_LOOKUP_TOKEN: ${ADDRESS_LOOKUP_TOKEN}
        IDAM_SERVICE_KEY: ${CCD_API_GATEWAY_S2S_SECRET}
        IDAM_OAUTH2_CLIENT_SECRET: ${CCD_API_GATEWAY_IDAM_CLIENT_SECRET}
        PROXY_DOCUMENT_MANAGEMENT: http://dm-store-aat.service.core-compute-aat.internal
      ingressHost: gateway-${SERVICE_NAME}.preview.platform.hmcts.net
      ingressIP: ${INGRESS_IP}
      keyVaults: []
  ccd-data-store-api:
    java:
      releaseNameOverride: ${SERVICE_NAME}-ccd-data-store-api
      imagePullPolicy: Always
      devcpuRequests: 1000m
      devmemoryRequests: 2048Mi
      devmemoryLimits: 4096Mi
      environment:
        CASE_DOCUMENT_AM_API_ATTACH_DOCUMENT_ENABLED: false
        DATA_STORE_DB_NAME: "{{ .Values.global.databaseNamePrefix }}data-store"
        DATA_STORE_DB_HOST: "{{ .Values.global.postgresHostname }}"
        DATA_STORE_DB_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
        DATA_STORE_IDAM_KEY: ${CCD_DATA_STORE_S2S_SECRET}
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,civil_service,ccd_case_document_am_api,aac_manage_case_assignment,wa_task_management_api,wa_task_monitor,wa_case_event_handler,wa_workflow_api,civil_general_applications
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service,aac_manage_case_assignment,civil_general_applications
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-aat.service.core-compute-aat.internal
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOSTS: ${SERVICE_NAME}-es-master:9200
        ELASTIC_SEARCH_DATA_NODES_HOSTS: http://${SERVICE_NAME}-es-master:9200
      secrets:
        DATA_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: false
      keyVaults: []
      ingressHost: ccd-data-store-api-${SERVICE_NAME}.preview.platform.hmcts.net


  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      releaseNameOverride: ${SERVICE_NAME}-ccd-definition-store-api
      environment:
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        DEFINITION_STORE_TX_TIMEOUT_DEFAULT: 60
        WELSH_TRANSLATION_ENABLED: false
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
        ELASTIC_SEARCH_ENABLED: true
        ELASTIC_SEARCH_HOST: ${SERVICE_NAME}-es-master
        ELASTIC_SEARCH_CASE_INDEX_MAPPING_FIELDS_LIMIT: 12000
        DEFINITION_STORE_DB_OPTIONS: "?stringtype=unspecified"
        DEFINITION_STORE_DB_NAME: "{{ .Values.global.databaseNamePrefix }}definition-store"
        DEFINITION_STORE_DB_HOST: "{{ .Values.global.postgresHostname }}"
        DEFINITION_STORE_DB_USERNAME: '{{ tpl .Values.global.postgresUsername $}}'
      secrets:
        DEFINITION_STORE_DB_PASSWORD:
          secretRef: "{{ .Values.global.postgresSecret }}"
          key: PASSWORD
          disabled: false
      keyVaults: []
      ingressHost: ccd-definition-store-${SERVICE_NAME}.preview.platform.hmcts.net


  postgresql:
    persistence:
      enabled: false

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    devcpuRequests: 500m
    devmemoryRequests: 512Mi
    devcpuLimits: 1
    devmemoryLimits: 1Gi
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    secrets:
      CAMUNDA_DB_PASSWORD:
        secretRef: postgres
        key: PASSWORD
        disabled: false
    environment:
      CAMUNDA_DB_HOST: civil-preview.postgres.database.azure.com
      CAMUNDA_DB_USER_NAME: hmcts
      CAMUNDA_DB_CONN_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
      CAMUNDA_DB_NAME: "pr-${CHANGE_ID}-camunda"
      TEMP_VAR: false


civil-wa:
  enabled: false

postgresql:
  enabled: true
  flexibleserver: civil-preview
  setup:
    databases:
      - name: "pr-${CHANGE_ID}-data-store"
      - name: "pr-${CHANGE_ID}-definition-store"
      - name: "pr-${CHANGE_ID}-user-profile"
      - name: "pr-${CHANGE_ID}-camunda"
      - name: "pr-${CHANGE_ID}-role-assignment"
      - name: "pr-${CHANGE_ID}-cft_task_db"
      - name: "pr-${CHANGE_ID}-wa-case-event-handler"
      - name: "pr-${CHANGE_ID}-wa_workflow_api"
      - name: "pr-${CHANGE_ID}-cmc"
