export enum ApplicationEvent {
  UPLOAD_ADDL_DOCUMENTS = 'UPLOAD_ADDL_DOCUMENTS',
  RESPOND_TO_JUDGE_ADDITIONAL_INFO = 'RESPOND_TO_JUDGE_ADDITIONAL_INFO',
  RESPOND_TO_JUDGE_DIRECTIONS = 'RESPOND_TO_JUDGE_DIRECTIONS',
  RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION = 'RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION',
}
