export enum ApplicationEvent {
  // TODO: Add events here for use by GA client
  NOTIFY_HELP_WITH_FEE = 'NOTIFY_HELP_WITH_FEE',
  UPLOAD_ADDL_DOCUMENTS = 'UPLOAD_ADDL_DOCUMENTS',
  RESPOND_TO_JUDGE_ADDITIONAL_INFO = 'RESPOND_TO_JUDGE_ADDITIONAL_INFO',
  RESPOND_TO_JUDGE_DIRECTIONS = 'RESPOND_TO_JUDGE_DIRECTIONS',
  RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION = 'RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION',
}
