export enum NoMediationReasonOptions {
  ALREADY_TRIED = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.ALREADY_TRIED',
  NOT_SURE = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.NOT_SURE',
  WOULD_NOT_SOLVE = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.WOULD_NOT_SOLVE',
  NO_DELAY_IN_HEARING = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.NO_DELAY_IN_HEARING',
  JUDGE_TO_DECIDE = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.JUDGE_TO_DECIDE',
  OTHER = 'PAGES.I_DON_T_WANT_FREE_MEDIATION.OTHER'
}
