export const Airlines = [
  { value: "Air India", text: "Air India", court: "Brentford" },
  { value: "Gulf Air", text: "Gulf Air", court: "Brentford" },
  { value: "Pakistan", text: "Pakistan", court: "Brentford" },
  { value: "Royal Jordanian", text: "Royal Jordanian", court: "Brentford" },
  { value: "Singapore Airlines", text: "Singapore Airlines", court: "Brentford" },
  { value: "Sri Lankan", text: "Sri Lankan", court: "Brentford" },
  { value: "Turkish", text: "Turkish", court: "Brentford" },
  { value: "Ukraine International", text: "Ukraine International", court: "Brentford" },
  { value: "Air China", text: "Air China", court: "Brentford" },
  { value: "Air Europa", text: "Air Europa", court: "CLCC" },
  { value: "Air Transat", text: "Air Transat", court: "CLCC" },
  { value: "China Airlines", text: "China Airlines", court: "CLCC" },
  { value: "China Eastern", text: "China Eastern", court: "CLCC" },
  { value: "El Al", text: "El Al", court: "CLCC" },
  { value: "Eva Air", text: "Eva Air", court: "CLCC" },
  { value: "Icelandair", text: "Icelandair", court: "CLCC" },
  { value: "Japan Airlines", text: "Japan Airlines", court: "CLCC" },
  { value: "Korean", text: "Korean", court: "CLCC" },
  { value: "LOT", text: "LOT", court: "CLCC" },
  { value: "Luxair", text: "Luxair", court: "CLCC" },
  { value: "Middle East", text: "Middle East", court: "CLCC" },
  { value: "Royal Air Maroc", text: "Royal Air Maroc", court: "CLCC" },
  { value: "Saudi Arabian Airlines", text: "Saudi Arabian Airlines", court: "CLCC" },
  { value: "Saudia", text: "Saudia", court: "CLCC" },
  { value: "Thai Airways", text: "Thai Airways", court: "CLCC" },
  { value: "Vietnam Airlines", text: "Vietnam Airlines", court: "CLCC" },
  { value: "Air Baltic", text: "Air Baltic", court: "Horsham" },
  { value: "Aurigny", text: "Aurigny", court: "Horsham" },
  { value: "Eastern", text: "Eastern", court: "Horsham" },
  { value: "JetBlue", text: "JetBlue", court: "Horsham" },
  { value: "Norse", text: "Norse", court: "Horsham" },
  { value: "Norweigan", text: "Norweigan", court: "Horsham" },
  { value: "Phillipine Airlines",  text: "Phillipine Airlines", court: "Horsham" },
  { value: "Virgin", text: "Virgin", court: "Horsham" },
  { value: "WestJet", text: "WestJet", court: "Horsham" },
  { value: "Biman Bangladesh", text: "Biman Bangladesh", court: "Liverpool" },
  { value: "Etihad", text: "Etihad", court: "Liverpool" },
  { value: "Finnair", text: "Finnair", court: "Liverpool" },
  { value: "Qatar", text: "Qatar", court: "Liverpool" },
  { value: "Vueling", text: "Vueling", court: "Liverpool" },
  { value: "Blue Air", text: "Blue Air", court: "Liverpool" },
  { value: "Play", text: "Play", court: "Liverpool" },
  { value: "Ryanair", text: "Ryanair", court: "Liverpool" },
  { value: "WizzAir", text: "WizzAir", court: "Liverpool" },
  { value: "Air Moldova", text: "Air Moldova", court: "Luton" },
  { value: "Avianca", text: "Avianca", court: "Luton" },
  { value: "Easyjet", text: "Easyjet", court: "Luton" },
  { value: "Pegasus", text: "Pegasus", court: "Luton" },
  { value: "Smartwings", text: "Smartwings", court: "Luton" },
  { value: "TUI / Thomson ", text: "TUI / Thomson ", court: "Luton" },
  { value: "Air Portugal", text: "Air Portugal", court: "Manchester" },
  { value: "Condor", text: "Condor", court: "Manchester" },
  { value: "Emirates", text: "Emirates", court: "Manchester" },
  { value: "Jet2.com", text: "Jet2.com", court: "Manchester" },
  { value: "Loganair", text: "Loganair", court: "Manchester" },
  { value: "Oman", text: "Oman", court: "Manchester" },
  { value: "Aegean", text: "Aegean", court: "Staines" },
  { value: "Aeroflot", text: "Aeroflot", court: "Staines" },
  { value: "Air Canada", text: "Air Canada", court: "Staines" },
  { value: "Air France", text: "Air France", court: "Staines" },
  { value: "Air Malta", text: "Air Malta", court: "Staines" },
  { value: "Bulgaria Air", text: "Bulgaria Air", court: "Staines" },
  { value: "Croatia Airlines", text: "Croatia Airlines", court: "Staines" },
  { value: "ITA", text: "ITA", court: "Staines" },
  { value: "Kenya Airways", text: "Kenya Airways", court: "Staines" },
  { value: "KLM", text: "KLM", court: "Staines" },
  { value: "LATAM/JJ", text: "LATAM/JJ", court: "Staines" },
  { value: "SAS", text: "SAS", court: "Staines" },
  { value: "Sky Express", text: "Sky Express", court: "Staines" },
  { value: "Wideroe", text: "Wideroe", court: "Staines" },
  { value: "Aer Lingus", text: "Aer Lingus", court: "Uxbridge" },
  { value: "Aeromexico", text: "Aeromexico", court: "Uxbridge" },
  { value: "American Airlines", text: "American Airlines", court: "Uxbridge" },
  { value: "Austrian Airways", text: "Austrian Airways", court: "Uxbridge" },
  { value: "BA/Cityflyer", text: "BA/Cityflyer", court: "Uxbridge" },
  { value: "Brussels	", text: "Brussels	", court: "Uxbridge" },
  { value: "China Southern", text: "China Southern", court: "Uxbridge" },
  { value: "Eurowings", text: "Eurowings", court: "Uxbridge" },
  { value: "Garuda", text: "Garuda", court: "Uxbridge" },
  { value: "Iberia/Express", text: "Iberia/Express", court: "Uxbridge" },
  { value: "Kuwait Airways", text: "Kuwait Airways", court: "Uxbridge" },
  { value: "Lufthansa", text: "Lufthansa", court: "Uxbridge" },
  { value: "SAS", text: "SAS", court: "Uxbridge" },
  { value: "Swiss International", text: "Swiss International", court: "Uxbridge" },
  { value: "United", text: "United", court: "Uxbridge" },
  { value: "Air Algerie", text: "Air Algerie", court: "Wandsworth" },
  { value: "Air New Zealande", text: "Air New Zealande", court: "Wandsworth" },
  { value: "All Nippon Airwayse", text: "All Nippon Airwayse", court: "Wandsworth" },
  { value: "Azerbaijan Airlines", text: "Azerbaijan Airlines", court: "Wandsworth" },
  { value: "Cathay Pacific", text: "Cathay Pacific", court: "Wandsworth" },
  { value: "Egyptair", text: "Egyptair", court: "Wandsworth" },
  { value: "Iran Air", text: "Iran Air", court: "Wandsworth" },
  { value: "Malaysian", text: "Malaysian", court: "Wandsworth" },
  { value: "Quantas", text: "Quantas", court: "Wandsworth" },
  { value: "Royal Brunei", text: "Royal Brunei", court: "Wandsworth" },
  { value: "South African Airways", text: "South African Airways", court: "Wandsworth" },
  { value: "Vistara", text: "Vistara", court: "Wandsworth" },
  { value: "Tunisair", text: "Tunisair", court: "Wandsworth" },
  { value: "Delta", text: "Delta", court: "Wandsworth" },
  { value: "Other", text: "Other", court: null },
];
