webChat:
  cnbc:
    uuid: 'script_1191773643670e666a982030.90013235'
    tenant: 'aG1jdHN4MTAx'
    channel: 'NBC_CNBC_Web_Chat'
    channelUuid: 'YFOOn2KASGSaEd96HY8-BA'
    buttonContainerId: '__8x8-chat-button-container-script_1191773643670e666a982030.90013235'
  mediation:
    uuid: 'script_202736819566d85c96c386f8.18964185'
    tenant: 'aG1jdHN4MTAx'
    channel: 'NBC_Mediation_Webchat'
    channelUuid: 'EfkT-IMvRReo_VGNJ5ietQ'
    buttonContainerId: '__8x8-chat-button-container-script_202736819566d85c96c386f8.18964185'
