import './assets/scss/main.scss';
import './assets/js/postcode-lookup.js';
import './assets/js/append-row.js';
import './assets/js/calculate-amount.js';
import './assets/js/calculate-length-repayment.js';
import './assets/js/calculate-total-amount.js';
import './assets/js/remove-error-content';
import './assets/js/conditionally-hide-add-button';
import './assets/js/select-toggle';
import './assets/js/reindex-add-another-actions';
import './assets/js/language-toggle';
import { initAll as initGovukFrontend } from 'govuk-frontend';
import { initAll as initMojFrontend } from '@ministryofjustice/frontend';
import './modules/cookie/cookieConfig';
import './assets/js/cookies-controller.js';
import './assets/js/disable-submit.js';
import './assets/js/multi-file-upload.js';
import { initAutoUploadFile } from './assets/js/auto-upload-file.js';

initGovukFrontend();
initMojFrontend();
initAutoUploadFile();
