export enum ExpenseType {
  OTHER = 'other expense',
  MORTGAGE = 'mortgage',
  MORTGAGE_PRIORITY = 'Mortgage',
  RENT = 'rent',
  RENT_PRIORITY = 'Rent',
  MAINTENANCE_PAYMENTS = 'maintenance payments',
  MAINTENANCE_PAYMENTS_PRIORITY = 'Maintenance payments',
  COUNCIL_TAX = 'Council Tax',
  COUNCIL_TAX_OR_COMMUNITY_CHARGE = 'Council Tax or Community Charge',
  GAS = 'gas',
  GAS_PRIORITY = 'Gas',
  ELECTRICITY = 'electricity',
  ELECTRICITY_PRIORITY = 'Electricity',
  WATER = 'water',
  WATER_PRIORITY = 'Water',
  TRAVEL = 'travel',
  SCHOOL_COSTS = 'school costs (include clothing)',
  FOOD_HOUSEKEEPING = 'food and housekeeping',
  TV_AND_BROADBAND = 'TV and broadband',
  HIRE_PURCHASES = 'hire purchase',
  MOBILE_PHONE = 'mobile phone',
}
