export const RESPONSEFORNOTPAIDPAYIMMEDIATELY: { [key: string]: string } = {
  'yes': 'PAGES.CHECK_YOUR_ANSWER.I_ACCEPT_THIS_AMOUNT',
  'no': 'PAGES.CHECK_YOUR_ANSWER.I_REJECT_THIS_AMOUNT',
};

export const RESPONSEFORHOWDOYOUWANTTOPROCEED: { [key: string]: string } = {
  SIGN_A_SETTLEMENT_AGREEMENT: 'PAGES.CHECK_YOUR_ANSWER.SIGN_SETTLEMENT',
  REQUEST_A_CCJ: 'PAGES.CHECK_YOUR_ANSWER.REQUEST_A_CCJ',
};
