export const RESPONSEFORNOTPAIDPAYIMMEDIATELY: { [key: string]: string } = {
  'yes': 'PAGES.CHECK_YOUR_ANSWER.I_ACCEPT_THIS_AMOUNT',
  'no': 'PAGES.CHECK_YOUR_ANSWER.I_REJECT_THIS_AMOUNT',
};

export const RESPONSEFORREPAYMENTPLAN: { [key: string]: string } = {
  'yes': 'PAGES.CHECK_YOUR_ANSWER.I_ACCEPT_THIS_REPAYMENT_PLAN',
  'no': 'PAGES.CHECK_YOUR_ANSWER.I_REJECT_THIS_REPAYMENT_PLAN',
};

export const RESPONSEFREQUENCY: { [key: string]: string } = {
  'WEEK': 'COMMON.PAYMENT_FREQUENCY.EVERY_WEEK',
  'TWO_WEEKS': 'COMMON.PAYMENT_FREQUENCY.TWO_WEEKS',
  'MONTH': 'COMMON.PAYMENT_FREQUENCY.MONTH',
};
