export const PageUrls = {

  //Page URL's for the CUI Common Pages.
  HOME: '/',
  DASHBOARD: '/dashboard',
  //Page URL's for the CUI Functional Pages.
  DEFENDANT : '/dashboard/:cuiCaseId/defendant',
  TASK_LIST : '/case/:cuiCaseId/response/task-list',
  BASE_CASE_URL : '/case/:cuiCaseId',
  BASE_CLAIM_URL : '/claim',
  BASE_FIRST_CONTACT_URL : '/first-contact',
  BASE_CASE_RESPONSE_URL : '/case/:cuiCaseId/response',
  BASE_CASE_PAID_IN_FULL_URL : '/case/:cuiCaseId/paid-in-full',
  STATEMENT_OF_MEANS_URL : '/case/:cuiCaseId/response/statement-of-means',
  MEDIATION_URL : '/case/:cuiCaseId/mediation',
  DIRECTIONS_QUESTIONNAIRE_URL : '/case/:cuiCaseId/directions-questionnaire',
  FULL_REJECTION_URL : '/case/:cuiCaseId/response/full-rejection',
  PARTIAL_ADMISSION_URL : '/case/:cuiCaseId/response/partial-admission',
  FULL_ADMISSION_URL : '/case/:cuiCaseId/response/full-admission',
  DATE_PAID_URL : '/case/:cuiCaseId/paid-in-full/date-paid',
  DATE_PAID_CONFIRMATION_URL : '/case/:cuiCaseId/paid-in-full/confirmation',
  CITIZEN_PHONE_NUMBER_URL : '/case/:cuiCaseId/response/your-phone',
  DOB_URL : '/case/:cuiCaseId/response/your-dob',
  CLAIM_DETAILS_URL : '/case/:cuiCaseId/response/claim-details',
  CITIZEN_DETAILS_URL : '/case/:cuiCaseId/response/your-details',
  POSTCODE_LOOKUP_URL : '/postcode-lookup',
  CITIZEN_RESPONSE_TYPE_URL : '/case/:cuiCaseId/response/response-type',
  CITIZEN_DISABILITY_URL : '/case/:cuiCaseId/response/statement-of-means/disability',
  CITIZEN_SEVERELY_DISABLED_URL : '/case/:cuiCaseId/response/statement-of-means/severe-disability',
  CITIZEN_RESIDENCE_URL : '/case/:cuiCaseId/response/statement-of-means/residence',
  CITIZEN_PARTNER_URL : '/case/:cuiCaseId/response/statement-of-means/partner/partner',
  CITIZEN_PARTNER_AGE_URL : '/case/:cuiCaseId/response/statement-of-means/partner/partner-age',
  CITIZEN_PARTNER_PENSION_URL : '/case/:cuiCaseId/response/statement-of-means/partner/partner-pension',
  CITIZEN_PARTNER_DISABILITY_URL : '/case/:cuiCaseId/response/statement-of-means/partner/partner-disability',
  CITIZEN_PARTNER_SEVERE_DISABILITY_URL : '/case/:cuiCaseId/response/statement-of-means/partner/partner-severe-disability',
  CITIZEN_DEPENDANTS_URL : '/case/:cuiCaseId/response/statement-of-means/dependants',
  CITIZEN_BANK_ACCOUNT_URL : '/case/:cuiCaseId/response/statement-of-means/bank-accounts',
  CITIZEN_OTHER_DEPENDANTS_URL : '/case/:cuiCaseId/response/statement-of-means/other-dependants',
  CITIZEN_EMPLOYMENT_URL : '/case/:cuiCaseId/response/statement-of-means/employment',
  CITIZEN_WHO_EMPLOYS_YOU_URL : '/case/:cuiCaseId/response/statement-of-means/employment/employers',
  CITIZEN_UNEMPLOYED_URL : '/case/:cuiCaseId/response/statement-of-means/unemployment',
  CITIZEN_SELF_EMPLOYED_URL : '/case/:cuiCaseId/response/statement-of-means/employment/self-employment',
  ON_TAX_PAYMENTS_URL : '/case/:cuiCaseId/response/statement-of-means/employment/self-employment/on-tax-payments',
  FINANCIAL_DETAILS_URL : '/case/:cuiCaseId/response/statement-of-means/intro',
  RESPONSE_TASK_LIST_URL : '/case/:cuiCaseId/response/task-list',
  CONFIRMATION_URL : '/case/:cuiCaseId/response/confirmation',
  CITIZEN_PAYMENT_OPTION_URL : '/case/:cuiCaseId/response/full-admission/payment-option',
  CITIZEN_PAYMENT_DATE_URL : '/case/:cuiCaseId/response/full-admission/payment-date',
  CITIZEN_PA_PAYMENT_DATE_URL : '/case/:cuiCaseId/response/partial-admission/payment-date',
  CITIZEN_DEPENDANTS_EDUCATION_URL : '/case/:cuiCaseId/response/statement-of-means/dependants/education',
  CHILDREN_DISABILITY_URL : '/case/:cuiCaseId/response/statement-of-means/dependants/children-disability',
  CITIZEN_COURT_ORDERS_URL : '/case/:cuiCaseId/response/statement-of-means/court-orders',
  CITIZEN_PRIORITY_DEBTS_URL : '/case/:cuiCaseId/response/statement-of-means/priority-debts',
  CITIZEN_DEBTS_URL : '/case/:cuiCaseId/response/statement-of-means/debts',
  CITIZEN_MONTHLY_EXPENSES_URL : '/case/:cuiCaseId/response/statement-of-means/monthly-expenses',
  CITIZEN_MONTHLY_INCOME_URL : '/case/:cuiCaseId/response/statement-of-means/monthly-income',
  TOTAL_AMOUNT_CALCULATION_URL : '/total-income-expense-calculation',
  CITIZEN_REPAYMENT_PLAN_FULL_URL : '/case/:cuiCaseId/response/full-admission/payment-plan',
  CITIZEN_REPAYMENT_PLAN_PARTIAL_URL : '/case/:cuiCaseId/response/partial-admission/payment-plan',
  CITIZEN_WHY_DO_YOU_DISAGREE_URL : '/case/:cuiCaseId/response/partial-admission/why-do-you-disagree',
  CITIZEN_TIMELINE_URL : '/case/:cuiCaseId/response/timeline',
  CITIZEN_EVIDENCE_URL : '/case/:cuiCaseId/response/evidence',
  CITIZEN_CARER_URL : '/case/:cuiCaseId/response/statement-of-means/carer',
  CITIZEN_EXPLANATION_URL : '/case/:cuiCaseId/response/statement-of-means/explanation',
  CITIZEN_OWED_AMOUNT_URL : '/case/:cuiCaseId/response/partial-admission/how-much-do-you-owe',
  CITIZEN_ALREADY_PAID_URL : '/case/:cuiCaseId/response/partial-admission/already-paid',
  CITIZEN_PARTIAL_ADMISSION_PAYMENT_OPTION_URL : '/case/:cuiCaseId/response/partial-admission/payment-option',
  CITIZEN_AMOUNT_YOU_PAID_URL : '/case/:cuiCaseId/response/partial-admission/how-much-have-you-paid',
  MEDIATION_DISAGREEMENT_URL : '/case/:cuiCaseId/mediation/mediation-disagreement',
  DONT_WANT_FREE_MEDIATION_URL : '/case/:cuiCaseId/mediation/i-dont-want-free-mediation',
  CAN_WE_USE_URL : '/case/:cuiCaseId/mediation/can-we-use',
  CAN_WE_USE_COMPANY_URL : '/case/:cuiCaseId/mediation/can-we-use-company',
  CITIZEN_FREE_TELEPHONE_MEDIATION_URL : '/case/:cuiCaseId/mediation/free-telephone-mediation',
  MEDIATION_CONTACT_PERSON_CONFIRMATION_URL : '/case/:cuiCaseId/mediation/mediation-contact-person',
  CITIZEN_REJECT_ALL_CLAIM_URL : '/case/:cuiCaseId/response/reject-all-of-claim',
  CITIZEN_CONTACT_THEM_URL : '/dashboard/:cuiCaseId/contact-them',
  RESPONSE_CHECK_ANSWERS_URL : '/case/:cuiCaseId/response/check-and-send',
  RESPONSE_YOUR_DEFENCE_URL : '/case/:cuiCaseId/response/your-defence',
  CITIZEN_FULL_REJECTION_YOU_PAID_LESS_URL : '/case/:cuiCaseId/response/full-rejection/you-have-paid-less',
  CITIZEN_WHY_DO_YOU_DISAGREE_FULL_REJECTION_URL : '/case/:cuiCaseId/response/full-rejection/why-do-you-disagree',
  RESPONSE_INCOMPLETE_SUBMISSION_URL : '/case/:cuiCaseId/response/incomplete-submission',
  CITIZEN_FR_AMOUNT_YOU_PAID_URL : '/case/:cuiCaseId/response/full-rejection/how-much-have-you-paid',
  DEFENDANT_SUMMARY_URL : '/dashboard/:cuiCaseId/defendant',
  DEFENDANT_DOCUMENTS_URL : '/dashboard/:cuiCaseId/defendant#documents',
  BILINGUAL_LANGUAGE_PREFERENCE_URL : '/case/:cuiCaseId/response/bilingual-language-preference',
  EXPERT_GUIDANCE_URL : '/case/:cuiCaseId/directions-questionnaire/expert-guidance',
  PERMISSION_FOR_EXPERT_URL : '/case/:cuiCaseId/directions-questionnaire/permission-for-expert',
  SUPPORT_REQUIRED_URL : '/case/:cuiCaseId/directions-questionnaire/support-required',
  CASE_TIMELINE_DOCUMENTS_URL : '/case/:cuiCaseId/documents/timeline/:documentId',
  CASE_DOCUMENT_DOWNLOAD_URL : '/case/:cuiCaseId/documents/:documentId',
  VULNERABILITY_URL : '/case/:cuiCaseId/directions-questionnaire/vulnerability',
  UNDERSTANDING_RESPONSE_OPTIONS_URL : '/case/:cuiCaseId/response/understanding-your-options',
  RESPONSE_DEADLINE_OPTIONS_URL : '/case/:cuiCaseId/response/response-deadline-options',
  AGREED_TO_MORE_TIME_URL : '/case/:cuiCaseId/response/agreed-to-more-time',
  REQUEST_MORE_TIME_URL : '/case/:cuiCaseId/response/request-more-time',
  NEW_RESPONSE_DEADLINE_URL : '/case/:cuiCaseId/response/new-response-deadline',
  FIRST_CONTACT_SIGNPOSTING_URL : '/first-contact/start',
  FIRST_CONTACT_CLAIM_REFERENCE_URL : '/first-contact/claim-reference',
  FIRST_CONTACT_CLAIM_SUMMARY_URL : '/first-contact/claim-summary',
  FIRST_CONTACT_ACCESS_DENIED_URL : '/first-contact/access-denied',
  FIRST_CONTACT_PIN_URL : '/first-contact/pin',
  DQ_CONSIDER_CLAIMANT_DOCUMENTS_URL : '/case/:cuiCaseId/directions-questionnaire/consider-claimant-documents',
  DQ_COURT_LOCATION_URL : '/case/:cuiCaseId/directions-questionnaire/court-location',
  DQ_DEFENDANT_EXPERT_EVIDENCE_URL : '/case/:cuiCaseId/directions-questionnaire/expert-evidence',
  DQ_DEFENDANT_WITNESSES_URL : '/case/:cuiCaseId/directions-questionnaire/defendant-witnesses',
  DQ_EXPERT_DETAILS_URL : '/case/:cuiCaseId/directions-questionnaire/expert-details',
  DQ_EXPERT_EXAMINATION_URL : '/case/:cuiCaseId/directions-questionnaire/expert-examination',
  DQ_GIVE_EVIDENCE_YOURSELF_URL : '/case/:cuiCaseId/directions-questionnaire/give-evidence-yourself',
  DQ_REQUEST_EXTRA_4WEEKS_URL : '/case/:cuiCaseId/directions-questionnaire/request-extra-4-weeks',
  DQ_EXPERT_SMALL_CLAIMS_URL : '/case/:cuiCaseId/directions-questionnaire/expert',
  DQ_EXPERT_REPORT_DETAILS_URL : '/case/:cuiCaseId/directions-questionnaire/expert-report-details',
  DQ_SHARE_AN_EXPERT_URL : '/case/:cuiCaseId/directions-questionnaire/shared-expert',
  DQ_TRIED_TO_SETTLE_CLAIM_URL : '/case/:cuiCaseId/directions-questionnaire/tried-to-settle',
  DQ_EXPERT_CAN_STILL_EXAMINE_URL : '/case/:cuiCaseId/directions-questionnaire/expert-can-still-examine',
  DQ_SENT_EXPERT_REPORTS_URL : '/case/:cuiCaseId/directions-questionnaire/sent-expert-reports',
  DQ_AVAILABILITY_DATES_FOR_HEARING_URL : '/case/:cuiCaseId/directions-questionnaire/availability-dates',
  DQ_EXPERT_GUIDANCE_URL : '/case/:cuiCaseId/directions-questionnaire/expert-guidance',
  DQ_WELSH_LANGUAGE_URL : '/case/:cuiCaseId/directions-questionnaire/welsh-language',
  DQ_UNAVAILABLE_FOR_HEARING_URL : '/case/:cuiCaseId/directions-questionnaire/unavailable-for-hearing',
  DQ_PHONE_OR_VIDEO_HEARING_URL : '/case/:cuiCaseId/directions-questionnaire/phone-or-video-hearing',
  DQ_NEXT_12MONTHS_CAN_NOT_HEARING_URL : '/case/:cuiCaseId/directions-questionnaire/cant-attend-hearing-in-next-12-months',

  /**
   * Page URL's for the Case Progression Functional Pages.
   * */

  //Evidence Upload
  CASE_PROGRESSION_TASK_LIST : '/case/:caseProgressionCaseId/defendant',
  UPLOAD_YOUR_DOCUMENTS : '/case/:caseProgressionCaseId/case-progression/upload-your-documents',
  WHAT_TYPE_OF_DOCUMENTS_DO_YOU_WANT_TO_UPLOAD : '/case/:caseProgressionCaseId/case-progression/type-of-documents',
  UPLOAD_DOCUMENTS : '/case/:caseProgressionCaseId/case-progression/upload-documents',
  CHECK_AND_SEND : '/case/:caseProgressionCaseId/case-progression/check-and-send',
  DOCUMENTS_UPLOADED : '/case/:caseProgressionCaseId/case-progression/documents-uploaded',

  //Trial Arrangements
  FINALISE_TRIAL_ARRANGEMENTS : '/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements',
  IS_CASE_READY : '/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements/is-case-ready',
  HAS_ANYTHING_CHANGED : '/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements/has-anything-changed',
  HEARING_DURATION_OTHER_INFO :'/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements/hearing-duration-other-info',
  CHECK_TRIAL_ARRANGEMENTS :'/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements/check-trial-arrangements',
  TRIAL_ARRANGEMENTS_CONFIRMATION : '/case/:caseProgressionCaseId/case-progression/finalise-trial-arrangements/confirmation',
} as const;
