import * as urls from 'routes/urls';

export const IGNORED_URLS = [
  urls.SIGN_IN_URL,
  urls.SIGN_OUT_URL,
  urls.CALLBACK_URL,
  urls.CASES_URL,
  urls.POSTCODE_LOOKUP_URL,
  urls.CITIZEN_DETAILS_URL,
  urls.DASHBOARD_URL,
  urls.CASE_TIMELINE_DOCUMENTS_URL,
  urls.CASE_DOCUMENT_DOWNLOAD_URL,
  urls.CLAIMANT_SOLE_TRADER_DETAILS_URL,
  urls.CLAIMANT_ORGANISATION_DETAILS_URL,
  urls.CLAIMANT_COMPANY_DETAILS_URL,
  urls.CLAIMANT_INDIVIDUAL_DETAILS_URL,
  urls.CLAIM_CHECK_ANSWERS_URL,
  urls.CLAIM_INTEREST_TOTAL_URL,
  urls.DEFENDANT_SUMMARY_URL,
];
