export enum CaseRole {
  CREATOR = '[CREATOR]',
  APPLICANTSOLICITORONE = '[APPLICANTSOLICITORONE]',
  RESPONDENTSOLICITORONE = '[RESPONDENTSOLICITORONE]',
  RESPONDENTSOLICITORTWO = '[RESPONDENTSOLICITORTWO]',
  CLAIMANT = '[CLAIMANT]',
  DEFENDANT = '[DEFENDANT]',
}
