export enum TaskStatus {
  ACTION_NEEDED = 'ACTION_NEEDED',
  COMPLETE = 'COMPLETE',
  INCOMPLETE = 'INCOMPLETE',
  DONE = 'DONE',
  DONE_NO_URL = 'DONE',
  READY_TO_VIEW = 'READY_TO_VIEW',
  NOT_AVAILABLE_YET = 'NOT_AVAILABLE_YET',
  IN_PROGRESS = 'IN_PROGRESS',
  UNAVAILABLE = 'UNAVAILABLE'
}
